name: Make package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Bootstrap
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Cache Theos
        uses: actions/cache@v3
        with:
          path: ~/theos
          key: ${{ runner.os }}-theos-${{ hashFiles('**/install-theos') }}

      - name: Install Theos
        if: steps.cache.outputs.cache-hit != 'true'
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.msT }}

      - name: Make Bootstrap Package
        run: make package

      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: Rolling Release
          tag_name: ${{ env.msT }}
          body: These are automatically updated builds of the latest commit.
          artifacts: "./packages/*"
          tag: release-${{ github.run_id }}
